### PR TITLE
Bump symfony framework bundle 6.0

### PR DESCRIPTION
**Pull request by romainf**
This PR allow installation with Symfony 6.0 app.

I see no conflics from symfony/framework-bundle changelog ( https://github.com/symfony/framework-bundle/blob/6.0/CHANGELOG.md#60 )

### CODE REVIEW

**Comment by endelwar** [comment]
Thanks for this PR! Could you please expand CI test for Symfony 6.0 on PHP 8.0/8.1 in `.github/workflows/CI.yaml`?

**Comment by romainf** [comment]
> Thanks for this PR! Could you please expand CI test for Symfony 6.0 on PHP 8.0/8.1 in `.github/workflows/CI.yaml`?

I try (first time with gh actions)

**Comment by endelwar** [comment]
Thanks, I've update php-weasyprint and require-dev versions.

Released as 1.2.0

**Comment by romainf** [comment]
Thanks a lot 👍

**Pull request merged**
